// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"
	transactioner "ebookstore/utils/transactioner"

	mock "github.com/stretchr/testify/mock"
)

// ITransactionProvider is an autogenerated mock type for the ITransactionProvider type
type ITransactionProvider struct {
	mock.Mock
}

// NewTransaction provides a mock function with given fields: ctx
func (_m *ITransactionProvider) NewTransaction(ctx context.Context) (transactioner.TxxProvider, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NewTransaction")
	}

	var r0 transactioner.TxxProvider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (transactioner.TxxProvider, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) transactioner.TxxProvider); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(transactioner.TxxProvider)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewITransactionProvider creates a new instance of ITransactionProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITransactionProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITransactionProvider {
	mock := &ITransactionProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
