// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"
	request "ebookstore/internal/model/request"

	mock "github.com/stretchr/testify/mock"
)

// ICustomerService is an autogenerated mock type for the ICustomerService type
type ICustomerService struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, customer
func (_m *ICustomerService) Login(ctx context.Context, customer request.Login) (string, error) {
	ret := _m.Called(ctx, customer)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.Login) (string, error)); ok {
		return rf(ctx, customer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.Login) string); ok {
		r0 = rf(ctx, customer)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.Login) error); ok {
		r1 = rf(ctx, customer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, customer
func (_m *ICustomerService) Register(ctx context.Context, customer *request.Register) (string, error) {
	ret := _m.Called(ctx, customer)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.Register) (string, error)); ok {
		return rf(ctx, customer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.Register) string); ok {
		r0 = rf(ctx, customer)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.Register) error); ok {
		r1 = rf(ctx, customer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewICustomerService creates a new instance of ICustomerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICustomerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICustomerService {
	mock := &ICustomerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
