// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	notification "ebookstore/utils/notification"

	mock "github.com/stretchr/testify/mock"
)

// INotificationService is an autogenerated mock type for the INotificationService type
type INotificationService struct {
	mock.Mock
}

// SendNotification provides a mock function with given fields: payload
func (_m *INotificationService) SendNotification(payload notification.EmailPayload) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for SendNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(notification.EmailPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewINotificationService creates a new instance of INotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewINotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *INotificationService {
	mock := &INotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
